import type { ReactNode } from "react";

import {
  buildGovernanceMetadata,
  type GovernanceAgent,
  type GovernanceBadge,
  type GovernanceTone,
} from "@/lib/education/governance";
import type { ArticleGovernance } from "@/lib/sanity";
import { cn } from "@/lib/utils";

/** Pill color per semantic tone — reuses the app's emerald/amber/rose scale. */
const TONE_STYLES: Record<GovernanceTone, string> = {
  success: "border-emerald-600/30 text-emerald-700 dark:text-emerald-400",
  warning: "border-amber-600/30 text-amber-700 dark:text-amber-400",
  danger: "border-rose-600/30 text-rose-700 dark:text-rose-400",
  neutral: "border-border text-foreground",
};

const TONE_DOTS: Record<GovernanceTone, string> = {
  success: "bg-emerald-500",
  warning: "bg-amber-500",
  danger: "bg-rose-500",
  neutral: "bg-muted-foreground",
};

interface GovernanceSidebarProps {
  /** Null/absent on documents published before governance existed. */
  governance?: ArticleGovernance | null;
  publishedAt: string;
}

/** A labelled pill, colored by tone, optionally led by a status dot. */
function Badge({
  badge,
  withDot = false,
}: {
  badge: GovernanceBadge;
  withDot?: boolean;
}) {
  return (
    <span
      className={cn(
        "inline-flex w-fit items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-xs font-medium uppercase tracking-wide",
        TONE_STYLES[badge.tone],
      )}
    >
      {withDot && (
        <span
          aria-hidden="true"
          className={cn("size-1.5 rounded-full", TONE_DOTS[badge.tone])}
        />
      )}
      {badge.label}
    </span>
  );
}

/** A pipeline agent: its role, with the powering model beneath. */
function Agent({ agent }: { agent: GovernanceAgent }) {
  return (
    <>
      <span className="block font-medium text-foreground">{agent.role}</span>
      {agent.poweredBy && (
        <span className="mt-0.5 block text-xs text-muted-foreground">
          {agent.poweredBy}
        </span>
      )}
    </>
  );
}

/** One label/value pair, stacked, divided from its neighbors. */
function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="grid gap-1.5 py-3.5 first:pt-0 last:pb-0">
      <dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
        {label}
      </dt>
      <dd className="text-sm text-foreground">{children}</dd>
    </div>
  );
}

/**
 * Content Governance panel for an article page: operational metadata for
 * a published Knowledge Asset — lifecycle status, AI quality assurance,
 * provenance, freshness, and the review cadence. Renders purely from a
 * `GovernanceMetadata` object, and skips fields that legacy documents
 * (published before governance existed) lack.
 */
export function GovernanceSidebar({
  governance,
  publishedAt,
}: GovernanceSidebarProps) {
  const metadata = buildGovernanceMetadata(governance, publishedAt);

  return (
    <aside
      aria-label="Content governance"
      className="h-fit rounded-lg border bg-card p-6 lg:sticky lg:top-24"
    >
      <h2 className="mb-4 font-serif text-lg font-normal tracking-tight">
        Content Governance
      </h2>
      <dl className="divide-y divide-border/60">
        <Field label="Status">
          <Badge badge={metadata.status} withDot />
        </Field>

        {metadata.reviewScore !== null && (
          <Field label="Review Score">
            <span className="flex items-baseline gap-1">
              <span className="font-serif text-2xl font-normal tracking-tight text-foreground">
                {metadata.reviewScore}
              </span>
              <span className="text-xs text-muted-foreground">/ 100</span>
            </span>
          </Field>
        )}

        {metadata.qualityRecommendation !== null && (
          <Field label="Review Outcome">
            <Badge badge={metadata.qualityRecommendation} />
          </Field>
        )}

        {metadata.contentFreshness !== null && (
          <Field label="Content Freshness">
            <span className="flex items-center gap-2">
              <Badge badge={metadata.contentFreshness.badge} />
              <span className="text-sm text-muted-foreground">
                ({metadata.contentFreshness.percent}%)
              </span>
            </span>
          </Field>
        )}

        {metadata.documentationVersion !== null && (
          <Field label="Documentation Version">
            <code className="inline-flex w-fit items-center rounded-md border border-border bg-muted px-1.5 py-0.5 font-mono text-xs text-foreground">
              {metadata.documentationVersion}
            </code>
          </Field>
        )}

        {metadata.generatedBy !== null && (
          <Field label="Generated By">
            <Agent agent={metadata.generatedBy} />
          </Field>
        )}

        {metadata.reviewedBy !== null && (
          <Field label="Reviewed By">
            <Agent agent={metadata.reviewedBy} />
          </Field>
        )}

        <Field label="Published">{metadata.publishedAt}</Field>

        {metadata.lastReviewedAt !== null && (
          <Field label="Last Reviewed">{metadata.lastReviewedAt}</Field>
        )}

        {metadata.nextReviewDue !== null && (
          <Field label="Next Review Due">{metadata.nextReviewDue}</Field>
        )}
      </dl>
    </aside>
  );
}
